//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossQuery.Linq.Tests.Mock.DB1_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
